### ISSUE TITLE
Adrian Wyatt - Project 2 Repo

### ISSUE THREAD

**Issue by Wyatt23** [ga-dc/wdi8-project2-gallery#16]
Link to repo: https://github.com/Wyatt23/GA-OutcomesProject2
Link to deployed app: (pending)

Things you'd like specific feedback on:

**Comment by amaseda** [comment]
### Re: Planning

:+1: Looks great. I think your tiers make sense and the ERD is manageable. There are some attributes in there, however, that may be better suited **NOT** as strings (e.g., boolean, datetime). That really depends, however, on how you interact with those values in your application.

Not required, but if you have time I encourage you to [look into Markdown](http://www.markdowntutorial.com/) so that the formatting in your `.md` files is a bit more readable. Useful in crafting a good readme.
